#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fase3_POO
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;


    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "BD_TIENDA_WEB_HAROLD")]
    public partial class BD_PAG_WEBDataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Definiciones de métodos de extensibilidad
        partial void OnCreated();
        partial void InsertCATEGORIAS(CATEGORIAS instance);
        partial void UpdateCATEGORIAS(CATEGORIAS instance);
        partial void DeleteCATEGORIAS(CATEGORIAS instance);
        partial void InsertCLIENTES(CLIENTES instance);
        partial void UpdateCLIENTES(CLIENTES instance);
        partial void DeleteCLIENTES(CLIENTES instance);
        partial void InsertCOMENTARIOS(COMENTARIOS instance);
        partial void UpdateCOMENTARIOS(COMENTARIOS instance);
        partial void DeleteCOMENTARIOS(COMENTARIOS instance);
        partial void InsertDETALLE_PEDIDO(DETALLE_PEDIDO instance);
        partial void UpdateDETALLE_PEDIDO(DETALLE_PEDIDO instance);
        partial void DeleteDETALLE_PEDIDO(DETALLE_PEDIDO instance);
        partial void InsertIMG_PRODUCTOS(IMG_PRODUCTOS instance);
        partial void UpdateIMG_PRODUCTOS(IMG_PRODUCTOS instance);
        partial void DeleteIMG_PRODUCTOS(IMG_PRODUCTOS instance);
        partial void InsertPEDIDOS(PEDIDOS instance);
        partial void UpdatePEDIDOS(PEDIDOS instance);
        partial void DeletePEDIDOS(PEDIDOS instance);
        partial void InsertPRODUCTOS(PRODUCTOS instance);
        partial void UpdatePRODUCTOS(PRODUCTOS instance);
        partial void DeletePRODUCTOS(PRODUCTOS instance);
        #endregion

        public BD_PAG_WEBDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_TIENDA_WEB_HAROLDConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }
        public BD_PAG_WEBDataContext(string connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public BD_PAG_WEBDataContext(System.Data.IDbConnection connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public BD_PAG_WEBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public BD_PAG_WEBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public System.Data.Linq.Table<CATEGORIAS> CATEGORIAS
        {
            get
            {
                return this.GetTable<CATEGORIAS>();
            }
        }

        public System.Data.Linq.Table<CLIENTES> CLIENTES
        {
            get
            {
                return this.GetTable<CLIENTES>();
            }
        }

        public System.Data.Linq.Table<COMENTARIOS> COMENTARIOS
        {
            get
            {
                return this.GetTable<COMENTARIOS>();
            }
        }

        public System.Data.Linq.Table<DETALLE_PEDIDO> DETALLE_PEDIDO
        {
            get
            {
                return this.GetTable<DETALLE_PEDIDO>();
            }
        }

        public System.Data.Linq.Table<IMG_PRODUCTOS> IMG_PRODUCTOS
        {
            get
            {
                return this.GetTable<IMG_PRODUCTOS>();
            }
        }

        public System.Data.Linq.Table<PEDIDOS> PEDIDOS
        {
            get
            {
                return this.GetTable<PEDIDOS>();
            }
        }

        public System.Data.Linq.Table<PRODUCTOS> PRODUCTOS
        {
            get
            {
                return this.GetTable<PRODUCTOS>();
            }
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_AGREGAR_ACTUALIZAR_CLIENTE")]
        public int SP_AGREGAR_ACTUALIZAR_CLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] ref System.Nullable<int> codCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(15)")] string idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(50)")] string apellido1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(50)")] string apellido2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(50)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(50)")] string provincia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(50)")] string canton, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string msj)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codCliente, idCliente, nombre, apellido1, apellido2, email, telefono, provincia, canton, direccion, fecha, msj);
            codCliente = ((System.Nullable<int>)(result.GetParameterValue(0)));
            msj = ((string)(result.GetParameterValue(11)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_AGREGAR_ACTUALIZAR_PEDIDO")]
        public int SP_AGREGAR_ACTUALIZAR_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] ref System.Nullable<int> codCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] ref System.Nullable<int> idPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Decimal(10,2)")] System.Nullable<decimal> costo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Decimal(3,1)")] System.Nullable<decimal> descuento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string msj)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codCliente, idPedido, costo, descuento, direccion, msj);
            codCliente = ((System.Nullable<int>)(result.GetParameterValue(0)));
            idPedido = ((System.Nullable<int>)(result.GetParameterValue(1)));
            msj = ((string)(result.GetParameterValue(5)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_AGREGAR_DETALLE_PEDIDO")]
        public int SP_AGREGAR_DETALLE_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> idPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string msj)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPedido, idProducto, msj);
            msj = ((string)(result.GetParameterValue(2)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_AGREGAR_MODIFICAR_COMENTARIO")]
        public int SP_AGREGAR_MODIFICAR_COMENTARIO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> idComentario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(300)")] string texto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> valoracion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string msj)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idComentario, idCliente, idProducto, texto, valoracion, msj);
            msj = ((string)(result.GetParameterValue(5)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_AGREGAR_MODIFICAR_PRODUCTO")]
        public int SP_AGREGAR_MODIFICAR_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(80)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> categoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Decimal(10,2)")] System.Nullable<decimal> costo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(80)")] string fabricante, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(300)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string msj)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, nombre, categoria, costo, fabricante, cantidad, descripcion, msj);
            msj = ((string)(result.GetParameterValue(7)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_ELIMINAR_CLIENTE")]
        public int SP_ELIMINAR_CLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> codCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string msj)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codCliente, msj);
            msj = ((string)(result.GetParameterValue(1)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_ELIMINAR_COMENTARIO")]
        public int SP_ELIMINAR_COMENTARIO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> idComentario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string msj)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idComentario, msj);
            msj = ((string)(result.GetParameterValue(1)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_ELIMINAR_DETALLE_PEDIDO")]
        public int SP_ELIMINAR_DETALLE_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> idPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string msj)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPedido, idProducto, msj);
            msj = ((string)(result.GetParameterValue(2)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_ELIMINAR_PEDIDO")]
        public int SP_ELIMINAR_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> idPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(200)")] ref string msj)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPedido, msj);
            msj = ((string)(result.GetParameterValue(1)));
            return ((int)(result.ReturnValue));
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.CATEGORIAS")]
    public partial class CATEGORIAS : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _ID_CATEGORIA;

        private string _NOMBRE_CATEGORIA;

        private string _DESCRIPCION_CATEGORIA;

        private EntitySet<PRODUCTOS> _PRODUCTOS;

        #region Definiciones de métodos de extensibilidad
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnID_CATEGORIAChanging(int value);
        partial void OnID_CATEGORIAChanged();
        partial void OnNOMBRE_CATEGORIAChanging(string value);
        partial void OnNOMBRE_CATEGORIAChanged();
        partial void OnDESCRIPCION_CATEGORIAChanging(string value);
        partial void OnDESCRIPCION_CATEGORIAChanged();
        #endregion

        public CATEGORIAS()
        {
            this._PRODUCTOS = new EntitySet<PRODUCTOS>(new Action<PRODUCTOS>(this.attach_PRODUCTOS), new Action<PRODUCTOS>(this.detach_PRODUCTOS));
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_CATEGORIA", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int ID_CATEGORIA
        {
            get
            {
                return this._ID_CATEGORIA;
            }
            set
            {
                if ((this._ID_CATEGORIA != value))
                {
                    this.OnID_CATEGORIAChanging(value);
                    this.SendPropertyChanging();
                    this._ID_CATEGORIA = value;
                    this.SendPropertyChanged("ID_CATEGORIA");
                    this.OnID_CATEGORIAChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NOMBRE_CATEGORIA", DbType = "VarChar(80) NOT NULL", CanBeNull = false)]
        public string NOMBRE_CATEGORIA
        {
            get
            {
                return this._NOMBRE_CATEGORIA;
            }
            set
            {
                if ((this._NOMBRE_CATEGORIA != value))
                {
                    this.OnNOMBRE_CATEGORIAChanging(value);
                    this.SendPropertyChanging();
                    this._NOMBRE_CATEGORIA = value;
                    this.SendPropertyChanged("NOMBRE_CATEGORIA");
                    this.OnNOMBRE_CATEGORIAChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCRIPCION_CATEGORIA", DbType = "VarChar(300)")]
        public string DESCRIPCION_CATEGORIA
        {
            get
            {
                return this._DESCRIPCION_CATEGORIA;
            }
            set
            {
                if ((this._DESCRIPCION_CATEGORIA != value))
                {
                    this.OnDESCRIPCION_CATEGORIAChanging(value);
                    this.SendPropertyChanging();
                    this._DESCRIPCION_CATEGORIA = value;
                    this.SendPropertyChanged("DESCRIPCION_CATEGORIA");
                    this.OnDESCRIPCION_CATEGORIAChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "CATEGORIAS_PRODUCTOS", Storage = "_PRODUCTOS", ThisKey = "ID_CATEGORIA", OtherKey = "CATEGORIA_PRODUCTO")]
        public EntitySet<PRODUCTOS> PRODUCTOS
        {
            get
            {
                return this._PRODUCTOS;
            }
            set
            {
                this._PRODUCTOS.Assign(value);
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private void attach_PRODUCTOS(PRODUCTOS entity)
        {
            this.SendPropertyChanging();
            entity.CATEGORIAS = this;
        }

        private void detach_PRODUCTOS(PRODUCTOS entity)
        {
            this.SendPropertyChanging();
            entity.CATEGORIAS = null;
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.CLIENTES")]
    public partial class CLIENTES : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _COD_CLIENTE;

        private string _ID_CLIENTE;

        private string _NOMBRE;

        private string _APELLIDO1;

        private string _APELLIDO2;

        private string _E_MAIL;

        private string _TELEFONO;

        private string _PROVINCIA;

        private string _CANTON;

        private string _DIRECCION;

        private System.DateTime _FECHA_NACIMIENTO;

        private System.Nullable<bool> _ESTADO;

        private EntitySet<COMENTARIOS> _COMENTARIOS;

        private EntitySet<PEDIDOS> _PEDIDOS;

        #region Definiciones de métodos de extensibilidad
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnCOD_CLIENTEChanging(int value);
        partial void OnCOD_CLIENTEChanged();
        partial void OnID_CLIENTEChanging(string value);
        partial void OnID_CLIENTEChanged();
        partial void OnNOMBREChanging(string value);
        partial void OnNOMBREChanged();
        partial void OnAPELLIDO1Changing(string value);
        partial void OnAPELLIDO1Changed();
        partial void OnAPELLIDO2Changing(string value);
        partial void OnAPELLIDO2Changed();
        partial void OnE_MAILChanging(string value);
        partial void OnE_MAILChanged();
        partial void OnTELEFONOChanging(string value);
        partial void OnTELEFONOChanged();
        partial void OnPROVINCIAChanging(string value);
        partial void OnPROVINCIAChanged();
        partial void OnCANTONChanging(string value);
        partial void OnCANTONChanged();
        partial void OnDIRECCIONChanging(string value);
        partial void OnDIRECCIONChanged();
        partial void OnFECHA_NACIMIENTOChanging(System.DateTime value);
        partial void OnFECHA_NACIMIENTOChanged();
        partial void OnESTADOChanging(System.Nullable<bool> value);
        partial void OnESTADOChanged();
        #endregion

        public CLIENTES()
        {
            this._COMENTARIOS = new EntitySet<COMENTARIOS>(new Action<COMENTARIOS>(this.attach_COMENTARIOS), new Action<COMENTARIOS>(this.detach_COMENTARIOS));
            this._PEDIDOS = new EntitySet<PEDIDOS>(new Action<PEDIDOS>(this.attach_PEDIDOS), new Action<PEDIDOS>(this.detach_PEDIDOS));
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COD_CLIENTE", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int COD_CLIENTE
        {
            get
            {
                return this._COD_CLIENTE;
            }
            set
            {
                if ((this._COD_CLIENTE != value))
                {
                    this.OnCOD_CLIENTEChanging(value);
                    this.SendPropertyChanging();
                    this._COD_CLIENTE = value;
                    this.SendPropertyChanged("COD_CLIENTE");
                    this.OnCOD_CLIENTEChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_CLIENTE", DbType = "VarChar(15) NOT NULL", CanBeNull = false)]
        public string ID_CLIENTE
        {
            get
            {
                return this._ID_CLIENTE;
            }
            set
            {
                if ((this._ID_CLIENTE != value))
                {
                    this.OnID_CLIENTEChanging(value);
                    this.SendPropertyChanging();
                    this._ID_CLIENTE = value;
                    this.SendPropertyChanged("ID_CLIENTE");
                    this.OnID_CLIENTEChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NOMBRE", DbType = "VarChar(50) NOT NULL", CanBeNull = false)]
        public string NOMBRE
        {
            get
            {
                return this._NOMBRE;
            }
            set
            {
                if ((this._NOMBRE != value))
                {
                    this.OnNOMBREChanging(value);
                    this.SendPropertyChanging();
                    this._NOMBRE = value;
                    this.SendPropertyChanged("NOMBRE");
                    this.OnNOMBREChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_APELLIDO1", DbType = "VarChar(50) NOT NULL", CanBeNull = false)]
        public string APELLIDO1
        {
            get
            {
                return this._APELLIDO1;
            }
            set
            {
                if ((this._APELLIDO1 != value))
                {
                    this.OnAPELLIDO1Changing(value);
                    this.SendPropertyChanging();
                    this._APELLIDO1 = value;
                    this.SendPropertyChanged("APELLIDO1");
                    this.OnAPELLIDO1Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_APELLIDO2", DbType = "VarChar(50) NOT NULL", CanBeNull = false)]
        public string APELLIDO2
        {
            get
            {
                return this._APELLIDO2;
            }
            set
            {
                if ((this._APELLIDO2 != value))
                {
                    this.OnAPELLIDO2Changing(value);
                    this.SendPropertyChanging();
                    this._APELLIDO2 = value;
                    this.SendPropertyChanged("APELLIDO2");
                    this.OnAPELLIDO2Changed();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_E_MAIL", DbType = "VarChar(50)")]
        public string E_MAIL
        {
            get
            {
                return this._E_MAIL;
            }
            set
            {
                if ((this._E_MAIL != value))
                {
                    this.OnE_MAILChanging(value);
                    this.SendPropertyChanging();
                    this._E_MAIL = value;
                    this.SendPropertyChanged("E_MAIL");
                    this.OnE_MAILChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TELEFONO", DbType = "VarChar(50)")]
        public string TELEFONO
        {
            get
            {
                return this._TELEFONO;
            }
            set
            {
                if ((this._TELEFONO != value))
                {
                    this.OnTELEFONOChanging(value);
                    this.SendPropertyChanging();
                    this._TELEFONO = value;
                    this.SendPropertyChanged("TELEFONO");
                    this.OnTELEFONOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_PROVINCIA", DbType = "VarChar(50) NOT NULL", CanBeNull = false)]
        public string PROVINCIA
        {
            get
            {
                return this._PROVINCIA;
            }
            set
            {
                if ((this._PROVINCIA != value))
                {
                    this.OnPROVINCIAChanging(value);
                    this.SendPropertyChanging();
                    this._PROVINCIA = value;
                    this.SendPropertyChanged("PROVINCIA");
                    this.OnPROVINCIAChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CANTON", DbType = "VarChar(50) NOT NULL", CanBeNull = false)]
        public string CANTON
        {
            get
            {
                return this._CANTON;
            }
            set
            {
                if ((this._CANTON != value))
                {
                    this.OnCANTONChanging(value);
                    this.SendPropertyChanging();
                    this._CANTON = value;
                    this.SendPropertyChanged("CANTON");
                    this.OnCANTONChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DIRECCION", DbType = "VarChar(200) NOT NULL", CanBeNull = false)]
        public string DIRECCION
        {
            get
            {
                return this._DIRECCION;
            }
            set
            {
                if ((this._DIRECCION != value))
                {
                    this.OnDIRECCIONChanging(value);
                    this.SendPropertyChanging();
                    this._DIRECCION = value;
                    this.SendPropertyChanged("DIRECCION");
                    this.OnDIRECCIONChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FECHA_NACIMIENTO", DbType = "Date NOT NULL")]
        public System.DateTime FECHA_NACIMIENTO
        {
            get
            {
                return this._FECHA_NACIMIENTO;
            }
            set
            {
                if ((this._FECHA_NACIMIENTO != value))
                {
                    this.OnFECHA_NACIMIENTOChanging(value);
                    this.SendPropertyChanging();
                    this._FECHA_NACIMIENTO = value;
                    this.SendPropertyChanged("FECHA_NACIMIENTO");
                    this.OnFECHA_NACIMIENTOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ESTADO", DbType = "Bit")]
        public System.Nullable<bool> ESTADO
        {
            get
            {
                return this._ESTADO;
            }
            set
            {
                if ((this._ESTADO != value))
                {
                    this.OnESTADOChanging(value);
                    this.SendPropertyChanging();
                    this._ESTADO = value;
                    this.SendPropertyChanged("ESTADO");
                    this.OnESTADOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "CLIENTES_COMENTARIOS", Storage = "_COMENTARIOS", ThisKey = "COD_CLIENTE", OtherKey = "ID_CLIENTE")]
        public EntitySet<COMENTARIOS> COMENTARIOS
        {
            get
            {
                return this._COMENTARIOS;
            }
            set
            {
                this._COMENTARIOS.Assign(value);
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "CLIENTES_PEDIDOS", Storage = "_PEDIDOS", ThisKey = "COD_CLIENTE", OtherKey = "COD_CLIENTE")]
        public EntitySet<PEDIDOS> PEDIDOS
        {
            get
            {
                return this._PEDIDOS;
            }
            set
            {
                this._PEDIDOS.Assign(value);
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private void attach_COMENTARIOS(COMENTARIOS entity)
        {
            this.SendPropertyChanging();
            entity.CLIENTES = this;
        }

        private void detach_COMENTARIOS(COMENTARIOS entity)
        {
            this.SendPropertyChanging();
            entity.CLIENTES = null;
        }

        private void attach_PEDIDOS(PEDIDOS entity)
        {
            this.SendPropertyChanging();
            entity.CLIENTES = this;
        }

        private void detach_PEDIDOS(PEDIDOS entity)
        {
            this.SendPropertyChanging();
            entity.CLIENTES = null;
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.COMENTARIOS")]
    public partial class COMENTARIOS : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _ID_COMENTARIO;

        private System.Nullable<int> _ID_CLIENTE;

        private System.Nullable<int> _ID_PRODUCTO;

        private string _TEXTO_COMENTARIO;

        private System.Nullable<int> _VALORACION;

        private EntityRef<CLIENTES> _CLIENTES;

        private EntityRef<PRODUCTOS> _PRODUCTOS;

        #region Definiciones de métodos de extensibilidad
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnID_COMENTARIOChanging(int value);
        partial void OnID_COMENTARIOChanged();
        partial void OnID_CLIENTEChanging(System.Nullable<int> value);
        partial void OnID_CLIENTEChanged();
        partial void OnID_PRODUCTOChanging(System.Nullable<int> value);
        partial void OnID_PRODUCTOChanged();
        partial void OnTEXTO_COMENTARIOChanging(string value);
        partial void OnTEXTO_COMENTARIOChanged();
        partial void OnVALORACIONChanging(System.Nullable<int> value);
        partial void OnVALORACIONChanged();
        #endregion

        public COMENTARIOS()
        {
            this._CLIENTES = default(EntityRef<CLIENTES>);
            this._PRODUCTOS = default(EntityRef<PRODUCTOS>);
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_COMENTARIO", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int ID_COMENTARIO
        {
            get
            {
                return this._ID_COMENTARIO;
            }
            set
            {
                if ((this._ID_COMENTARIO != value))
                {
                    this.OnID_COMENTARIOChanging(value);
                    this.SendPropertyChanging();
                    this._ID_COMENTARIO = value;
                    this.SendPropertyChanged("ID_COMENTARIO");
                    this.OnID_COMENTARIOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_CLIENTE", DbType = "Int")]
        public System.Nullable<int> ID_CLIENTE
        {
            get
            {
                return this._ID_CLIENTE;
            }
            set
            {
                if ((this._ID_CLIENTE != value))
                {
                    if (this._CLIENTES.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    this.OnID_CLIENTEChanging(value);
                    this.SendPropertyChanging();
                    this._ID_CLIENTE = value;
                    this.SendPropertyChanged("ID_CLIENTE");
                    this.OnID_CLIENTEChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_PRODUCTO", DbType = "Int")]
        public System.Nullable<int> ID_PRODUCTO
        {
            get
            {
                return this._ID_PRODUCTO;
            }
            set
            {
                if ((this._ID_PRODUCTO != value))
                {
                    if (this._PRODUCTOS.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    this.OnID_PRODUCTOChanging(value);
                    this.SendPropertyChanging();
                    this._ID_PRODUCTO = value;
                    this.SendPropertyChanged("ID_PRODUCTO");
                    this.OnID_PRODUCTOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TEXTO_COMENTARIO", DbType = "VarChar(300)")]
        public string TEXTO_COMENTARIO
        {
            get
            {
                return this._TEXTO_COMENTARIO;
            }
            set
            {
                if ((this._TEXTO_COMENTARIO != value))
                {
                    this.OnTEXTO_COMENTARIOChanging(value);
                    this.SendPropertyChanging();
                    this._TEXTO_COMENTARIO = value;
                    this.SendPropertyChanged("TEXTO_COMENTARIO");
                    this.OnTEXTO_COMENTARIOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_VALORACION", DbType = "Int")]
        public System.Nullable<int> VALORACION
        {
            get
            {
                return this._VALORACION;
            }
            set
            {
                if ((this._VALORACION != value))
                {
                    this.OnVALORACIONChanging(value);
                    this.SendPropertyChanging();
                    this._VALORACION = value;
                    this.SendPropertyChanged("VALORACION");
                    this.OnVALORACIONChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "CLIENTES_COMENTARIOS", Storage = "_CLIENTES", ThisKey = "ID_CLIENTE", OtherKey = "COD_CLIENTE", IsForeignKey = true)]
        public CLIENTES CLIENTES
        {
            get
            {
                return this._CLIENTES.Entity;
            }
            set
            {
                CLIENTES previousValue = this._CLIENTES.Entity;
                if (((previousValue != value)
                            || (this._CLIENTES.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._CLIENTES.Entity = null;
                        previousValue.COMENTARIOS.Remove(this);
                    }
                    this._CLIENTES.Entity = value;
                    if ((value != null))
                    {
                        value.COMENTARIOS.Add(this);
                        this._ID_CLIENTE = value.COD_CLIENTE;
                    }
                    else
                    {
                        this._ID_CLIENTE = default(Nullable<int>);
                    }
                    this.SendPropertyChanged("CLIENTES");
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PRODUCTOS_COMENTARIOS", Storage = "_PRODUCTOS", ThisKey = "ID_PRODUCTO", OtherKey = "ID_PRODUCTO", IsForeignKey = true)]
        public PRODUCTOS PRODUCTOS
        {
            get
            {
                return this._PRODUCTOS.Entity;
            }
            set
            {
                PRODUCTOS previousValue = this._PRODUCTOS.Entity;
                if (((previousValue != value)
                            || (this._PRODUCTOS.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._PRODUCTOS.Entity = null;
                        previousValue.COMENTARIOS.Remove(this);
                    }
                    this._PRODUCTOS.Entity = value;
                    if ((value != null))
                    {
                        value.COMENTARIOS.Add(this);
                        this._ID_PRODUCTO = value.ID_PRODUCTO;
                    }
                    else
                    {
                        this._ID_PRODUCTO = default(Nullable<int>);
                    }
                    this.SendPropertyChanged("PRODUCTOS");
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.DETALLE_PEDIDO")]
    public partial class DETALLE_PEDIDO : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _ID_DETALLE_PEDIDO;

        private int _ID_PEDIDO;

        private int _ID_PRODUCTO;

        private EntityRef<PEDIDOS> _PEDIDOS;

        private EntityRef<PRODUCTOS> _PRODUCTOS;

        #region Definiciones de métodos de extensibilidad
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnID_DETALLE_PEDIDOChanging(int value);
        partial void OnID_DETALLE_PEDIDOChanged();
        partial void OnID_PEDIDOChanging(int value);
        partial void OnID_PEDIDOChanged();
        partial void OnID_PRODUCTOChanging(int value);
        partial void OnID_PRODUCTOChanged();
        #endregion

        public DETALLE_PEDIDO()
        {
            this._PEDIDOS = default(EntityRef<PEDIDOS>);
            this._PRODUCTOS = default(EntityRef<PRODUCTOS>);
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_DETALLE_PEDIDO", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int ID_DETALLE_PEDIDO
        {
            get
            {
                return this._ID_DETALLE_PEDIDO;
            }
            set
            {
                if ((this._ID_DETALLE_PEDIDO != value))
                {
                    this.OnID_DETALLE_PEDIDOChanging(value);
                    this.SendPropertyChanging();
                    this._ID_DETALLE_PEDIDO = value;
                    this.SendPropertyChanged("ID_DETALLE_PEDIDO");
                    this.OnID_DETALLE_PEDIDOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_PEDIDO", DbType = "Int NOT NULL")]
        public int ID_PEDIDO
        {
            get
            {
                return this._ID_PEDIDO;
            }
            set
            {
                if ((this._ID_PEDIDO != value))
                {
                    if (this._PEDIDOS.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    this.OnID_PEDIDOChanging(value);
                    this.SendPropertyChanging();
                    this._ID_PEDIDO = value;
                    this.SendPropertyChanged("ID_PEDIDO");
                    this.OnID_PEDIDOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_PRODUCTO", DbType = "Int NOT NULL")]
        public int ID_PRODUCTO
        {
            get
            {
                return this._ID_PRODUCTO;
            }
            set
            {
                if ((this._ID_PRODUCTO != value))
                {
                    if (this._PRODUCTOS.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    this.OnID_PRODUCTOChanging(value);
                    this.SendPropertyChanging();
                    this._ID_PRODUCTO = value;
                    this.SendPropertyChanged("ID_PRODUCTO");
                    this.OnID_PRODUCTOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PEDIDOS_DETALLE_PEDIDO", Storage = "_PEDIDOS", ThisKey = "ID_PEDIDO", OtherKey = "ID_PEDIDO", IsForeignKey = true)]
        public PEDIDOS PEDIDOS
        {
            get
            {
                return this._PEDIDOS.Entity;
            }
            set
            {
                PEDIDOS previousValue = this._PEDIDOS.Entity;
                if (((previousValue != value)
                            || (this._PEDIDOS.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._PEDIDOS.Entity = null;
                        previousValue.DETALLE_PEDIDO.Remove(this);
                    }
                    this._PEDIDOS.Entity = value;
                    if ((value != null))
                    {
                        value.DETALLE_PEDIDO.Add(this);
                        this._ID_PEDIDO = value.ID_PEDIDO;
                    }
                    else
                    {
                        this._ID_PEDIDO = default(int);
                    }
                    this.SendPropertyChanged("PEDIDOS");
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PRODUCTOS_DETALLE_PEDIDO", Storage = "_PRODUCTOS", ThisKey = "ID_PRODUCTO", OtherKey = "ID_PRODUCTO", IsForeignKey = true)]
        public PRODUCTOS PRODUCTOS
        {
            get
            {
                return this._PRODUCTOS.Entity;
            }
            set
            {
                PRODUCTOS previousValue = this._PRODUCTOS.Entity;
                if (((previousValue != value)
                            || (this._PRODUCTOS.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._PRODUCTOS.Entity = null;
                        previousValue.DETALLE_PEDIDO.Remove(this);
                    }
                    this._PRODUCTOS.Entity = value;
                    if ((value != null))
                    {
                        value.DETALLE_PEDIDO.Add(this);
                        this._ID_PRODUCTO = value.ID_PRODUCTO;
                    }
                    else
                    {
                        this._ID_PRODUCTO = default(int);
                    }
                    this.SendPropertyChanged("PRODUCTOS");
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.IMG_PRODUCTOS")]
    public partial class IMG_PRODUCTOS : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _ID_IMG;

        private int _ID_PRODUCTO;

        private string _RUTA_IMG;

        private EntityRef<PRODUCTOS> _PRODUCTOS;

        #region Definiciones de métodos de extensibilidad
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnID_IMGChanging(int value);
        partial void OnID_IMGChanged();
        partial void OnID_PRODUCTOChanging(int value);
        partial void OnID_PRODUCTOChanged();
        partial void OnRUTA_IMGChanging(string value);
        partial void OnRUTA_IMGChanged();
        #endregion

        public IMG_PRODUCTOS()
        {
            this._PRODUCTOS = default(EntityRef<PRODUCTOS>);
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_IMG", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int ID_IMG
        {
            get
            {
                return this._ID_IMG;
            }
            set
            {
                if ((this._ID_IMG != value))
                {
                    this.OnID_IMGChanging(value);
                    this.SendPropertyChanging();
                    this._ID_IMG = value;
                    this.SendPropertyChanged("ID_IMG");
                    this.OnID_IMGChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_PRODUCTO", DbType = "Int NOT NULL")]
        public int ID_PRODUCTO
        {
            get
            {
                return this._ID_PRODUCTO;
            }
            set
            {
                if ((this._ID_PRODUCTO != value))
                {
                    if (this._PRODUCTOS.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    this.OnID_PRODUCTOChanging(value);
                    this.SendPropertyChanging();
                    this._ID_PRODUCTO = value;
                    this.SendPropertyChanged("ID_PRODUCTO");
                    this.OnID_PRODUCTOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RUTA_IMG", DbType = "VarChar(500) NOT NULL", CanBeNull = false)]
        public string RUTA_IMG
        {
            get
            {
                return this._RUTA_IMG;
            }
            set
            {
                if ((this._RUTA_IMG != value))
                {
                    this.OnRUTA_IMGChanging(value);
                    this.SendPropertyChanging();
                    this._RUTA_IMG = value;
                    this.SendPropertyChanged("RUTA_IMG");
                    this.OnRUTA_IMGChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PRODUCTOS_IMG_PRODUCTOS", Storage = "_PRODUCTOS", ThisKey = "ID_PRODUCTO", OtherKey = "ID_PRODUCTO", IsForeignKey = true)]
        public PRODUCTOS PRODUCTOS
        {
            get
            {
                return this._PRODUCTOS.Entity;
            }
            set
            {
                PRODUCTOS previousValue = this._PRODUCTOS.Entity;
                if (((previousValue != value)
                            || (this._PRODUCTOS.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._PRODUCTOS.Entity = null;
                        previousValue.IMG_PRODUCTOS.Remove(this);
                    }
                    this._PRODUCTOS.Entity = value;
                    if ((value != null))
                    {
                        value.IMG_PRODUCTOS.Add(this);
                        this._ID_PRODUCTO = value.ID_PRODUCTO;
                    }
                    else
                    {
                        this._ID_PRODUCTO = default(int);
                    }
                    this.SendPropertyChanged("PRODUCTOS");
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.PEDIDOS")]
    public partial class PEDIDOS : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _ID_PEDIDO;

        private int _COD_CLIENTE;

        private System.Nullable<decimal> _DESCUENTO_PEDIDO;

        private decimal _COSTO_TOTAL;

        private System.DateTime _FECHA_PEDIDO;

        private bool _ESTADO_PEDIDO;

        private string _DIRECCION_ENVIO;

        private EntitySet<DETALLE_PEDIDO> _DETALLE_PEDIDO;

        private EntityRef<CLIENTES> _CLIENTES;

        #region Definiciones de métodos de extensibilidad
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnID_PEDIDOChanging(int value);
        partial void OnID_PEDIDOChanged();
        partial void OnCOD_CLIENTEChanging(int value);
        partial void OnCOD_CLIENTEChanged();
        partial void OnDESCUENTO_PEDIDOChanging(System.Nullable<decimal> value);
        partial void OnDESCUENTO_PEDIDOChanged();
        partial void OnCOSTO_TOTALChanging(decimal value);
        partial void OnCOSTO_TOTALChanged();
        partial void OnFECHA_PEDIDOChanging(System.DateTime value);
        partial void OnFECHA_PEDIDOChanged();
        partial void OnESTADO_PEDIDOChanging(bool value);
        partial void OnESTADO_PEDIDOChanged();
        partial void OnDIRECCION_ENVIOChanging(string value);
        partial void OnDIRECCION_ENVIOChanged();
        #endregion

        public PEDIDOS()
        {
            this._DETALLE_PEDIDO = new EntitySet<DETALLE_PEDIDO>(new Action<DETALLE_PEDIDO>(this.attach_DETALLE_PEDIDO), new Action<DETALLE_PEDIDO>(this.detach_DETALLE_PEDIDO));
            this._CLIENTES = default(EntityRef<CLIENTES>);
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_PEDIDO", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int ID_PEDIDO
        {
            get
            {
                return this._ID_PEDIDO;
            }
            set
            {
                if ((this._ID_PEDIDO != value))
                {
                    this.OnID_PEDIDOChanging(value);
                    this.SendPropertyChanging();
                    this._ID_PEDIDO = value;
                    this.SendPropertyChanged("ID_PEDIDO");
                    this.OnID_PEDIDOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COD_CLIENTE", DbType = "Int NOT NULL")]
        public int COD_CLIENTE
        {
            get
            {
                return this._COD_CLIENTE;
            }
            set
            {
                if ((this._COD_CLIENTE != value))
                {
                    if (this._CLIENTES.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    this.OnCOD_CLIENTEChanging(value);
                    this.SendPropertyChanging();
                    this._COD_CLIENTE = value;
                    this.SendPropertyChanged("COD_CLIENTE");
                    this.OnCOD_CLIENTEChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCUENTO_PEDIDO", DbType = "Decimal(3,1)")]
        public System.Nullable<decimal> DESCUENTO_PEDIDO
        {
            get
            {
                return this._DESCUENTO_PEDIDO;
            }
            set
            {
                if ((this._DESCUENTO_PEDIDO != value))
                {
                    this.OnDESCUENTO_PEDIDOChanging(value);
                    this.SendPropertyChanging();
                    this._DESCUENTO_PEDIDO = value;
                    this.SendPropertyChanged("DESCUENTO_PEDIDO");
                    this.OnDESCUENTO_PEDIDOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COSTO_TOTAL", DbType = "Decimal(10,2) NOT NULL")]
        public decimal COSTO_TOTAL
        {
            get
            {
                return this._COSTO_TOTAL;
            }
            set
            {
                if ((this._COSTO_TOTAL != value))
                {
                    this.OnCOSTO_TOTALChanging(value);
                    this.SendPropertyChanging();
                    this._COSTO_TOTAL = value;
                    this.SendPropertyChanged("COSTO_TOTAL");
                    this.OnCOSTO_TOTALChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FECHA_PEDIDO", DbType = "Date NOT NULL")]
        public System.DateTime FECHA_PEDIDO
        {
            get
            {
                return this._FECHA_PEDIDO;
            }
            set
            {
                if ((this._FECHA_PEDIDO != value))
                {
                    this.OnFECHA_PEDIDOChanging(value);
                    this.SendPropertyChanging();
                    this._FECHA_PEDIDO = value;
                    this.SendPropertyChanged("FECHA_PEDIDO");
                    this.OnFECHA_PEDIDOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ESTADO_PEDIDO", DbType = "Bit NOT NULL")]
        public bool ESTADO_PEDIDO
        {
            get
            {
                return this._ESTADO_PEDIDO;
            }
            set
            {
                if ((this._ESTADO_PEDIDO != value))
                {
                    this.OnESTADO_PEDIDOChanging(value);
                    this.SendPropertyChanging();
                    this._ESTADO_PEDIDO = value;
                    this.SendPropertyChanged("ESTADO_PEDIDO");
                    this.OnESTADO_PEDIDOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DIRECCION_ENVIO", DbType = "VarChar(200) NOT NULL", CanBeNull = false)]
        public string DIRECCION_ENVIO
        {
            get
            {
                return this._DIRECCION_ENVIO;
            }
            set
            {
                if ((this._DIRECCION_ENVIO != value))
                {
                    this.OnDIRECCION_ENVIOChanging(value);
                    this.SendPropertyChanging();
                    this._DIRECCION_ENVIO = value;
                    this.SendPropertyChanged("DIRECCION_ENVIO");
                    this.OnDIRECCION_ENVIOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PEDIDOS_DETALLE_PEDIDO", Storage = "_DETALLE_PEDIDO", ThisKey = "ID_PEDIDO", OtherKey = "ID_PEDIDO")]
        public EntitySet<DETALLE_PEDIDO> DETALLE_PEDIDO
        {
            get
            {
                return this._DETALLE_PEDIDO;
            }
            set
            {
                this._DETALLE_PEDIDO.Assign(value);
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "CLIENTES_PEDIDOS", Storage = "_CLIENTES", ThisKey = "COD_CLIENTE", OtherKey = "COD_CLIENTE", IsForeignKey = true)]
        public CLIENTES CLIENTES
        {
            get
            {
                return this._CLIENTES.Entity;
            }
            set
            {
                CLIENTES previousValue = this._CLIENTES.Entity;
                if (((previousValue != value)
                            || (this._CLIENTES.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._CLIENTES.Entity = null;
                        previousValue.PEDIDOS.Remove(this);
                    }
                    this._CLIENTES.Entity = value;
                    if ((value != null))
                    {
                        value.PEDIDOS.Add(this);
                        this._COD_CLIENTE = value.COD_CLIENTE;
                    }
                    else
                    {
                        this._COD_CLIENTE = default(int);
                    }
                    this.SendPropertyChanged("CLIENTES");
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private void attach_DETALLE_PEDIDO(DETALLE_PEDIDO entity)
        {
            this.SendPropertyChanging();
            entity.PEDIDOS = this;
        }

        private void detach_DETALLE_PEDIDO(DETALLE_PEDIDO entity)
        {
            this.SendPropertyChanging();
            entity.PEDIDOS = null;
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.PRODUCTOS")]
    public partial class PRODUCTOS : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _ID_PRODUCTO;

        private string _NOMBRE_PRODUCTO;

        private int _CATEGORIA_PRODUCTO;

        private decimal _COSTO_PRODUCTO;

        private string _FABRICANTE;

        private int _CANTIDAD_STOCK;

        private string _DESCRIPCION;

        private EntitySet<COMENTARIOS> _COMENTARIOS;

        private EntitySet<DETALLE_PEDIDO> _DETALLE_PEDIDO;

        private EntitySet<IMG_PRODUCTOS> _IMG_PRODUCTOS;

        private EntityRef<CATEGORIAS> _CATEGORIAS;

        #region Definiciones de métodos de extensibilidad
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnID_PRODUCTOChanging(int value);
        partial void OnID_PRODUCTOChanged();
        partial void OnNOMBRE_PRODUCTOChanging(string value);
        partial void OnNOMBRE_PRODUCTOChanged();
        partial void OnCATEGORIA_PRODUCTOChanging(int value);
        partial void OnCATEGORIA_PRODUCTOChanged();
        partial void OnCOSTO_PRODUCTOChanging(decimal value);
        partial void OnCOSTO_PRODUCTOChanged();
        partial void OnFABRICANTEChanging(string value);
        partial void OnFABRICANTEChanged();
        partial void OnCANTIDAD_STOCKChanging(int value);
        partial void OnCANTIDAD_STOCKChanged();
        partial void OnDESCRIPCIONChanging(string value);
        partial void OnDESCRIPCIONChanged();
        #endregion

        public PRODUCTOS()
        {
            this._COMENTARIOS = new EntitySet<COMENTARIOS>(new Action<COMENTARIOS>(this.attach_COMENTARIOS), new Action<COMENTARIOS>(this.detach_COMENTARIOS));
            this._DETALLE_PEDIDO = new EntitySet<DETALLE_PEDIDO>(new Action<DETALLE_PEDIDO>(this.attach_DETALLE_PEDIDO), new Action<DETALLE_PEDIDO>(this.detach_DETALLE_PEDIDO));
            this._IMG_PRODUCTOS = new EntitySet<IMG_PRODUCTOS>(new Action<IMG_PRODUCTOS>(this.attach_IMG_PRODUCTOS), new Action<IMG_PRODUCTOS>(this.detach_IMG_PRODUCTOS));
            this._CATEGORIAS = default(EntityRef<CATEGORIAS>);
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID_PRODUCTO", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int ID_PRODUCTO
        {
            get
            {
                return this._ID_PRODUCTO;
            }
            set
            {
                if ((this._ID_PRODUCTO != value))
                {
                    this.OnID_PRODUCTOChanging(value);
                    this.SendPropertyChanging();
                    this._ID_PRODUCTO = value;
                    this.SendPropertyChanged("ID_PRODUCTO");
                    this.OnID_PRODUCTOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NOMBRE_PRODUCTO", DbType = "VarChar(80) NOT NULL", CanBeNull = false)]
        public string NOMBRE_PRODUCTO
        {
            get
            {
                return this._NOMBRE_PRODUCTO;
            }
            set
            {
                if ((this._NOMBRE_PRODUCTO != value))
                {
                    this.OnNOMBRE_PRODUCTOChanging(value);
                    this.SendPropertyChanging();
                    this._NOMBRE_PRODUCTO = value;
                    this.SendPropertyChanged("NOMBRE_PRODUCTO");
                    this.OnNOMBRE_PRODUCTOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CATEGORIA_PRODUCTO", DbType = "Int NOT NULL")]
        public int CATEGORIA_PRODUCTO
        {
            get
            {
                return this._CATEGORIA_PRODUCTO;
            }
            set
            {
                if ((this._CATEGORIA_PRODUCTO != value))
                {
                    if (this._CATEGORIAS.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    this.OnCATEGORIA_PRODUCTOChanging(value);
                    this.SendPropertyChanging();
                    this._CATEGORIA_PRODUCTO = value;
                    this.SendPropertyChanged("CATEGORIA_PRODUCTO");
                    this.OnCATEGORIA_PRODUCTOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_COSTO_PRODUCTO", DbType = "Decimal(10,2) NOT NULL")]
        public decimal COSTO_PRODUCTO
        {
            get
            {
                return this._COSTO_PRODUCTO;
            }
            set
            {
                if ((this._COSTO_PRODUCTO != value))
                {
                    this.OnCOSTO_PRODUCTOChanging(value);
                    this.SendPropertyChanging();
                    this._COSTO_PRODUCTO = value;
                    this.SendPropertyChanged("COSTO_PRODUCTO");
                    this.OnCOSTO_PRODUCTOChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FABRICANTE", DbType = "VarChar(80)")]
        public string FABRICANTE
        {
            get
            {
                return this._FABRICANTE;
            }
            set
            {
                if ((this._FABRICANTE != value))
                {
                    this.OnFABRICANTEChanging(value);
                    this.SendPropertyChanging();
                    this._FABRICANTE = value;
                    this.SendPropertyChanged("FABRICANTE");
                    this.OnFABRICANTEChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CANTIDAD_STOCK", DbType = "Int NOT NULL")]
        public int CANTIDAD_STOCK
        {
            get
            {
                return this._CANTIDAD_STOCK;
            }
            set
            {
                if ((this._CANTIDAD_STOCK != value))
                {
                    this.OnCANTIDAD_STOCKChanging(value);
                    this.SendPropertyChanging();
                    this._CANTIDAD_STOCK = value;
                    this.SendPropertyChanged("CANTIDAD_STOCK");
                    this.OnCANTIDAD_STOCKChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DESCRIPCION", DbType = "VarChar(300) NOT NULL", CanBeNull = false)]
        public string DESCRIPCION
        {
            get
            {
                return this._DESCRIPCION;
            }
            set
            {
                if ((this._DESCRIPCION != value))
                {
                    this.OnDESCRIPCIONChanging(value);
                    this.SendPropertyChanging();
                    this._DESCRIPCION = value;
                    this.SendPropertyChanged("DESCRIPCION");
                    this.OnDESCRIPCIONChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PRODUCTOS_COMENTARIOS", Storage = "_COMENTARIOS", ThisKey = "ID_PRODUCTO", OtherKey = "ID_PRODUCTO")]
        public EntitySet<COMENTARIOS> COMENTARIOS
        {
            get
            {
                return this._COMENTARIOS;
            }
            set
            {
                this._COMENTARIOS.Assign(value);
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PRODUCTOS_DETALLE_PEDIDO", Storage = "_DETALLE_PEDIDO", ThisKey = "ID_PRODUCTO", OtherKey = "ID_PRODUCTO")]
        public EntitySet<DETALLE_PEDIDO> DETALLE_PEDIDO
        {
            get
            {
                return this._DETALLE_PEDIDO;
            }
            set
            {
                this._DETALLE_PEDIDO.Assign(value);
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PRODUCTOS_IMG_PRODUCTOS", Storage = "_IMG_PRODUCTOS", ThisKey = "ID_PRODUCTO", OtherKey = "ID_PRODUCTO")]
        public EntitySet<IMG_PRODUCTOS> IMG_PRODUCTOS
        {
            get
            {
                return this._IMG_PRODUCTOS;
            }
            set
            {
                this._IMG_PRODUCTOS.Assign(value);
            }
        }

        [global::System.Data.Linq.Mapping.AssociationAttribute(Name = "CATEGORIAS_PRODUCTOS", Storage = "_CATEGORIAS", ThisKey = "CATEGORIA_PRODUCTO", OtherKey = "ID_CATEGORIA", IsForeignKey = true)]
        public CATEGORIAS CATEGORIAS
        {
            get
            {
                return this._CATEGORIAS.Entity;
            }
            set
            {
                CATEGORIAS previousValue = this._CATEGORIAS.Entity;
                if (((previousValue != value)
                            || (this._CATEGORIAS.HasLoadedOrAssignedValue == false)))
                {
                    this.SendPropertyChanging();
                    if ((previousValue != null))
                    {
                        this._CATEGORIAS.Entity = null;
                        previousValue.PRODUCTOS.Remove(this);
                    }
                    this._CATEGORIAS.Entity = value;
                    if ((value != null))
                    {
                        value.PRODUCTOS.Add(this);
                        this._CATEGORIA_PRODUCTO = value.ID_CATEGORIA;
                    }
                    else
                    {
                        this._CATEGORIA_PRODUCTO = default(int);
                    }
                    this.SendPropertyChanged("CATEGORIAS");
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private void attach_COMENTARIOS(COMENTARIOS entity)
        {
            this.SendPropertyChanging();
            entity.PRODUCTOS = this;
        }

        private void detach_COMENTARIOS(COMENTARIOS entity)
        {
            this.SendPropertyChanging();
            entity.PRODUCTOS = null;
        }

        private void attach_DETALLE_PEDIDO(DETALLE_PEDIDO entity)
        {
            this.SendPropertyChanging();
            entity.PRODUCTOS = this;
        }

        private void detach_DETALLE_PEDIDO(DETALLE_PEDIDO entity)
        {
            this.SendPropertyChanging();
            entity.PRODUCTOS = null;
        }

        private void attach_IMG_PRODUCTOS(IMG_PRODUCTOS entity)
        {
            this.SendPropertyChanging();
            entity.PRODUCTOS = this;
        }

        private void detach_IMG_PRODUCTOS(IMG_PRODUCTOS entity)
        {
            this.SendPropertyChanging();
            entity.PRODUCTOS = null;
        }
    }
}
#pragma warning restore 1591
