
CREATE DATABASE BD_TIENDA_WEB_HAROLD
GO

USE BD_TIENDA_WEB_HAROLD
GO

--CREACIÓN DE TABLAS

CREATE TABLE CLIENTES(
	COD_CLIENTE int IDENTITY(1,1), -- PK
	ID_CLIENTE varchar(15) NOT NULL UNIQUE, 
	NOMBRE varchar(50) NOT NULL,
	APELLIDO1 varchar(50) NOT NULL,
	APELLIDO2 varchar(50) NOT NULL,
	E_MAIL varchar(50) UNIQUE,
	TELEFONO varchar(50),
	PROVINCIA varchar(50),
	CANTON varchar(50),
	DIRECCION varchar(200) NOT NULL,
	FECHA_NACIMIENTO date NOT NULL,
	ESTADO bit DEFAULT 1
);

CREATE TABLE CATEGORIAS(
	ID_CATEGORIA int IDENTITY (1,1),-- PK
	NOMBRE_CATEGORIA varchar(80) NOT NULL,
	DESCRIPCION_CATEGORIA varchar(300),
);

CREATE TABLE PRODUCTOS(
	ID_PRODUCTO int IDENTITY(1,1),-- PK
	NOMBRE_PRODUCTO varchar(80) NOT NULL,
	CATEGORIA_PRODUCTO int NOT NULL,
	COSTO_PRODUCTO decimal (10,2) NOT NULL DEFAULT 0,
	FABRICANTE varchar(80),
	CANTIDAD_STOCK int NOT NULL DEFAULT 0,
	DESCRIPCION varchar(300) NOT NULL

);

CREATE TABLE PEDIDOS(
	ID_PEDIDO int IDENTITY(1,1),-- PK
	COD_CLIENTE int NOT NULL, --FK
	DESCUENTO_PEDIDO decimal(3,1) DEFAULT 0,
	COSTO_TOTAL decimal(10,2) NOT NULL DEFAULT 0,
	FECHA_PEDIDO date NOT NULL DEFAULT GETDATE(),
	ESTADO_PEDIDO bit NOT NULL DEFAULT 1,
	DIRECCION_ENVIO varchar(200) NOT NULL
);

CREATE TABLE DETALLE_PEDIDO(
	ID_PEDIDO int NOT NULL,-- PK FK
	ID_PRODUCTO int NOT NULL,-- PK FK
	CANTIDAD_PRODUCTOS int NOT NULL DEFAULT 1
);

CREATE TABLE COMENTARIOS(
	ID_COMENTARIO int IDENTITY(1,1), --PK
	ID_CLIENTE int,--FK
	ID_PRODUCTO int,--FK
	TEXTO_COMENTARIO varchar(300),
	VALORACION int DEFAULT 0
);

--ALTERACIÓN DE LAS TABLAS

ALTER TABLE CLIENTES
ADD CONSTRAINT PK_COD_CLIENTE PRIMARY KEY(COD_CLIENTE),
	CONSTRAINT CK_E_MAIL CHECK (E_MAIL LIKE '%@%'),
	CONSTRAINT CK_PROVINCIA CHECK (PROVINCIA IN('Alajuela','Heredia','Guanacaste','San José','Puntarenas','Limón','Cartago')),
	CONSTRAINT CK_EDAD CHECK (DATEDIFF(year, '1999-06-29', GETDATE()) >=18);

ALTER TABLE CATEGORIAS
ADD CONSTRAINT PK_ID_CATEGORIA PRIMARY KEY (ID_CATEGORIA),
	CONSTRAINT CK_CATEGORIA CHECK (NOMBRE_CATEGORIA IN ('Electrónica', 'Accesorios','Hogar'));

ALTER TABLE PRODUCTOS
ADD CONSTRAINT PK_ID_PRODUCTO PRIMARY KEY(ID_PRODUCTO),
	CONSTRAINT FK_ID_CATEGORIA FOREIGN KEY (CATEGORIA_PRODUCTO) REFERENCES CATEGORIAS(ID_CATEGORIA);

ALTER TABLE PEDIDOS
ADD CONSTRAINT PK_ID_PEDIDO PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT FK_COD_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE);

ALTER TABLE DETALLE_PEDIDO
ADD CONSTRAINT PK_ID_DETALLE_PEDIDO PRIMARY KEY (ID_PEDIDO,ID_PRODUCTO),
	CONSTRAINT FK_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
	CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO);
	
ALTER TABLE COMENTARIOS
ADD CONSTRAINT PK_ID_COMENTARIO PRIMARY KEY (ID_COMENTARIO),
	CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE),
	CONSTRAINT FK_ID_PRODUCTO_COMENTARIO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
	CONSTRAINT CK_VALORACION CHECK (VALORACION IN (0,1,2,3,4,5));


--INSERCIÓN DE DATOS

INSERT INTO CLIENTES (ID_CLIENTE,NOMBRE,APELLIDO1,APELLIDO2,TELEFONO,E_MAIL,PROVINCIA,CANTON,DIRECCION,FECHA_NACIMIENTO) VALUES
('2000001','Andrés','Corrales','Pérez','88888881','2000001@outlook.com','Alajuela','Palmares','200 mts Norte del Banco Popular','1995-03-21'),
('2000002','Carlos','Marín','Herrera','88888882','2000002@outlook.com','Alajuela','San Ramón','Costado Oste del cementerio ','1986-05-24'),
('2000003','María','Vargas','Vargas','88888883','2000003@outlook.com','San José','San José','Barrio Escalante avenida 15','2001-01-30'),
('2000004','Cristian','Jiménez','Vargas','88888884','2000004@outlook.com','Puntarenas','Golfito','En la Guaria','1993-08-14'),
('2000005','Sofía','Alvarez','Muñoz','88888885','2000005@outlook.com','Cartago','Cartago','San Rafael Calle seis Avenida 1','1988-06-10');

INSERT INTO CATEGORIAS (NOMBRE_CATEGORIA,DESCRIPCION_CATEGORIA) VALUES
('Electrónica','Productos varios de tecnología como celulares, computadoras, electrodomésticos'),
('Accesorios','Productos varios como collares, aretes, colonias'),
('Hogar','Productos varios para el hogar como muebles, fundas, cortinas');

INSERT INTO PRODUCTOS(NOMBRE_PRODUCTO,CATEGORIA_PRODUCTO,CANTIDAD_STOCK,FABRICANTE,COSTO_PRODUCTO,DESCRIPCION) VALUES
('Motherboard b450 DS3h ',1,5,'Gigabyte',40000,'Producto en buen estado, con daños leves en la caja'),
('Mouse G305 ',1,10,'Logitech',20000,'Producto en buen estado, con daños leves en la caja'),
('Headset HS80 ',1,7,'Corsair',45000,'Producto en buen estado, con daños leves en la caja'),
('Cable USB C ',1,10,'AON',1500,'Producto en buen estado'),
('Collar de Corazón',2,4,NULL,6000,'Material de Acero bañado en oro'),
('Cadena Guadalupe',2,3,NULL,5500,'Materia de Acero'),
('Pulsera con Cruz',2,1,NULL,8000,'Cadena con Perlas'),
('Cortinas blancas',3,3,NULL,15000,'Dimensión 120x250 color blanco traslucida'),
('Cama Individual',3,2,NULL,120000,'Hecha de Madera barnizada'),
('Tapete para baño',3,8,NULL,6000,'Color Azul'),
('Espejo mediano',3,4,NULL,10000,'Marco de Madera 50cm');

INSERT INTO COMENTARIOS (ID_CLIENTE,ID_PRODUCTO,TEXTO_COMENTARIO,VALORACION) VALUES
(3,6,'Excelente',5),
(3,1,'Muy bien',4),
(2,1,'Bien',3),
(1,6,'Muy bien',4),
(4,11,'Bien',3),
(2,11,'Excelente',5);

/*
SELECT * FROM CLIENTES
SELECT * FROM CATEGORIAS
SELECT * FROM PRODUCTOS
SELECT * FROM COMENTARIOS
*/

